services:
  - type: web
    name: purohit-darpan-backend
    image: ghcr.io/krishnenduchakraborty49/purohit-darpan-backend:latest
    plan: free
    region: ohio
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: purohit-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: purohit-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: purohit-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: purohit-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: purohit-db
          property: password
      - key: CORS_ALLOWED_ORIGINS
        value: https://purohit-darpan-frontend.vercel.app

databases:
  - name: purohit-db
    plan: free
    region: ohio