services:
  - type: web
    name: purohit-darpan-backend
    runtime: java
    plan: free
    region: ohio
    buildCommand: mvn clean package -DskipTests
    startCommand: java -Xmx400m -Xms64m -XX:+UseSerialGC -Dserver.port=$PORT -Dserver.address=0.0.0.0 -jar target/purohit-darpan-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        value: ep-raspy-thunder-apmzpbny-pooler.c-7.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_tN1VK8mzayWr
      - key: CORS_ALLOWED_ORIGINS
        value: https://purohit-darpan-frontend.vercel.app