CREATE OR REPLACE FUNCTION update_timestamp() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $$ language 'plpgsql';

DROP TABLE IF EXISTS user_notification_preferences, notification_logs, user_saved_events, panchang_cache, hindu_festivals, pdf_annotations, video_bookmarks, user_highlights, user_step_notes, user_puja_progress, ai_feedback, ai_query_logs, step_samagri, step_mantras, resources, puja_steps, samagri, mantras, pujas, users CASCADE;

CREATE TABLE users (id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, username VARCHAR(100) NOT NULL UNIQUE, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, full_name VARCHAR(200) NOT NULL, role VARCHAR(50) NOT NULL DEFAULT 'STUDENT', profile_picture VARCHAR(500), preferred_format VARCHAR(50) DEFAULT 'DOC', fcm_token VARCHAR(500), notifications_enabled BOOLEAN DEFAULT TRUE, is_active BOOLEAN DEFAULT TRUE, last_login TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TRIGGER update_users_timestamp BEFORE UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE TABLE pujas (id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, name VARCHAR(300) NOT NULL, name_devanagari VARCHAR(300), description TEXT, duration_minutes INT, difficulty VARCHAR(50) DEFAULT 'BEGINNER', category VARCHAR(200), thumbnail_url VARCHAR(500), is_active BOOLEAN DEFAULT TRUE, created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_pujas_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL);
CREATE TRIGGER update_pujas_timestamp BEFORE UPDATE ON pujas FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE TABLE puja_steps (id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, puja_id BIGINT NOT NULL, step_order INT NOT NULL, title VARCHAR(300) NOT NULL, title_devanagari VARCHAR(300), title_bengali VARCHAR(300), title_sanskrit VARCHAR(300), description TEXT, video_url VARCHAR(500), video_transcript TEXT, pdf_resource_id BIGINT, duration_seconds INT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_steps_puja FOREIGN KEY (puja_id) REFERENCES pujas(id) ON DELETE CASCADE);
CREATE TRIGGER update_puja_steps_timestamp BEFORE UPDATE ON puja_steps FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE TABLE mantras (id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, shlok_text TEXT NOT NULL, transliteration TEXT, word_meanings JSONB, audio_url VARCHAR(500), source_text VARCHAR(300), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE step_mantras (id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, step_id BIGINT NOT NULL, mantra_id BIGINT NOT NULL, sequence_order INT NOT NULL DEFAULT 1, CONSTRAINT fk_sm_step FOREIGN KEY (step_id) REFERENCES puja_steps(id) ON DELETE CASCADE, CONSTRAINT fk_sm_mantra FOREIGN KEY (mantra_id) REFERENCES mantras(id) ON DELETE CASCADE);
CREATE TABLE samagri (id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, name VARCHAR(300) NOT NULL, name_devanagari VARCHAR(300), description TEXT, image_url VARCHAR(500), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE step_samagri (id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, step_id BIGINT NOT NULL, samagri_id BIGINT NOT NULL, quantity VARCHAR(100), notes VARCHAR(500), CONSTRAINT fk_ss_step FOREIGN KEY (step_id) REFERENCES puja_steps(id) ON DELETE CASCADE, CONSTRAINT fk_ss_samagri FOREIGN KEY (samagri_id) REFERENCES samagri(id) ON DELETE CASCADE);
CREATE TABLE resources (id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, puja_id BIGINT, title VARCHAR(300) NOT NULL, resource_type VARCHAR(50) NOT NULL DEFAULT 'PDF', file_url VARCHAR(500) NOT NULL, file_size_kb INT, page_count INT, table_of_contents JSONB, is_downloadable BOOLEAN DEFAULT FALSE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_res_puja FOREIGN KEY (puja_id) REFERENCES pujas(id) ON DELETE SET NULL);
ALTER TABLE puja_steps ADD CONSTRAINT fk_steps_pdf_resource FOREIGN KEY (pdf_resource_id) REFERENCES resources(id) ON DELETE SET NULL;
CREATE TABLE hindu_festivals (id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, name VARCHAR(300) NOT NULL, name_devanagari VARCHAR(300), description TEXT, puja_id BIGINT, event_date DATE NOT NULL, days_duration INT NOT NULL DEFAULT 1, notification_days_before INT NOT NULL DEFAULT 20, is_active BOOLEAN DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_hf_puja FOREIGN KEY (puja_id) REFERENCES pujas(id) ON DELETE SET NULL);
